# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rmvn_bayes_cpp 
#' 
#' Fast sampling from multivar. normal dist'ns for Bayesian hierarchical
#' models. 
#'  
#' \code{rmvn_bayes_cpp} samples from a MV normal of the form 
#' N(A^(-1) * b, A^(-1)).
#' 
#' @param A Precision matrix of the desired sample. 
#' @param b Vector s.t. mean of desired sample is A^(-1) * b 
#' 
#' @export 
rmvn_bayes_cpp <- function(A, b) {
    .Call('nucleaRmcmc_rmvn_bayes_cpp', PACKAGE = 'nucleaRmcmc', A, b)
}

#' rm_sngl_vec_entry
#'
#' Fast conditional sampling multivar. normal vector entry given all others.
#' 
#' \code{rm_sngl_vec_entry} 
#' 
#' @param x vector
#' @param jOmit The index of the vector x which we'd like to omit from 
#' conditioning and sample) 
#' 
#' @export
rm_sngl_vec_entry <- function(x, jOmit) {
    .Call('nucleaRmcmc_rm_sngl_vec_entry', PACKAGE = 'nucleaRmcmc', x, jOmit)
}

#' Fast conditional sampling multivar. normal vector entry given all others.
#' 
#' \code{r_cond_mvn_cpp2} 
#' 
#' @param mu Mean vector of MVN distribution
#' @param cholSigma Cholesky decomposition of the covariance matrix of the MVN 
#' @param iSigma Precision matrix of the MVN
#' @param x Vector realization of MVN, with some conponents on which we want 
#' to condition
#' @param jOmit The index of the vector x which we'd like to omit from 
#' conditioning and sample) 
#' 
#' @export
rmvn_cond_cpp <- function(mu, cholSigma, iSigma, x, jOmit) {
    .Call('nucleaRmcmc_rmvn_cond_cpp', PACKAGE = 'nucleaRmcmc', mu, cholSigma, iSigma, x, jOmit)
}

